name: v4l2rtspserver
adopt-info: v4lserver
summary: RTSP and HTTP camera stream server
base: core20
description: |
  This is an streamer feed from
    - an Video4Linux device that support H264, HEVC, JPEG, VP8 or VP9 capture.
    - an ALSA device that support PCM S16_BE, S16_LE, S32_BE or S32_LE

  The RTSP server supports
    - RTP/UDP unicast
    - RTP/UDP multicast
    - RTP/TCP
    - RTP/RTSP/HTTP

  The HTTP server supports (available using -S option for capture format that
  could be muxed in Transport Stream)
    - HLS
    - MPEG-DASH

  To give the ssnap access to camera and audio capturing, use the following commands

    sudo snap connect v4l2rtspserver:camera
    sudo snap connect v4l2rtspserver:alsa

  Now you can start the daemon with

    sudo snap start --enable v4l2rtspserver

  Thre snap also ships a command to be used from CLI in case you do not want to
  use the server, this command is called v4l2rtspserver.manual

  For more information see the upstream README at
  https://github.com/mpromonet/v4l2rtspserver

grade: stable
confinement: strict

apps:
  v4l2rtspserver:
    command: usr/bin/v4l2rtspserver -S1
    daemon: simple
    install-mode: disable
    plugs:
      - camera
      - home
      - alsa
      - network
      - network-bind
  manual:
    command: usr/bin/v4l2rtspserver
    plugs:
      - camera
      - home
      - alsa
      - network
      - network-bind

layout:
  /usr/share/v4l2rtspserver:
    bind: $SNAP/usr/share/v4l2rtspserver
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  v4lserver:
    source: https://github.com/mpromonet/v4l2rtspserver.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - liblivemedia-dev
      - liblog4cpp5-dev
      - libasound2-dev
      - libssl-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - libbasicusageenvironment1
      - libgroupsock8
      - liblivemedia77
      - liblog4cpp5v5
      - libusageenvironment3
      - libssl1.1
    override-pull: |
      snapcraftctl pull
      VER="$(git describe --tags)"
      snapcraftctl set-version $VER
    prime:
      - -lib/systemd
    override-prime: |
      snapcraftctl prime
      find $SNAPCRAFT_PRIME/usr/share/doc/ ! -type d ! -name '*copyright*' | xargs rm
      mkdir -p $SNAPCRAFT_PRIME/usr/share/doc/v4l2wrapper
      cp $SNAPCRAFT_PART_SRC/v4l2wrapper/LICENSE $SNAPCRAFT_PRIME/usr/share/doc/v4l2wrapper/copyright
      mkdir -p $SNAPCRAFT_PRIME/usr/share/doc/v4l2rtspserver
      cp $SNAPCRAFT_PART_SRC/LICENSE $SNAPCRAFT_PRIME/usr/share/doc/v4l2rtspserver/copyright
